### ISSUE TITLE
[Bug] Permission for Call recording not respected

### ISSUE THREAD

**Issue by AlexD1979** [voicefoundryap/amazon-connect-for-zendesk#68]
**Describe the bug**
In the comments of a Zendesk ticket is a link pointing to the recording function from Connect with the voice recording. It seems, there is no rights check, if the agent are allowed by rights setup in their Connect Security Profile to access this data or not. This is a very big GDPR issue in Germany.

**To Reproduce**
1. Make a call with voice recording enabled to an agent
2. Ends the call
3. Wait until the CTR data are written to the ticket private comment field
4. The link points to the CAll Recording (Recording file: download (available within a few minutes after the call))

**Expected behavior**
The permissions set in the Security Profile will be respected, If the profile has no right on listen to call recordings, the permission should be denied.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 
 - Version latest from 20-Apr-21

**Additional context**

**Comment by agroblervf** [comment]
Hi @AlexD1979,
The link to both CTR and recording is always there but the access is managed by Connect internally: 

- If you're not currently logged into Connect session, you'll be prompted to login first, eg. when you just copy the link and paste into a new browser tab.
- If/when you're logged in but don't have sufficient permissions to access either recording or CTR, Connect will display an error message.

Same goes for embedded recording player. With insufficient permissions, or when not logged in the agent will see ` Recording not available ` instead of a normal Zendesk player UI.

Note that Connect allows granular access management via agent hierarchy in combination with security profiles. This enables giving access to recording to only agents within certain parts of the hierarchy (eg. same team).

**Comment by AlexD1979** [comment]
Thanks a lot, this was not clear to me. Then this case can be closed.
